# De teksten van de app, in vijf talen: (nl, en, fr, es, de).
#
# Genereer de XML-bestanden met:  python3 tools/make_strings.py
# De standaardmap `values/` is Engels, zodat elke taal die we niet kennen
# (Italiaans, Pools, …) Engels krijgt. Nederlands staat in `values-nl/`.
#
# Placeholders: %1$s voor tekst, %1$d voor getallen. Apostrofs en
# aanhalingstekens worden door het script zelf ge-escaped.

S = {
    # --- Algemeen -----------------------------------------------------------
    "app_name": ("Totem", "Totem", "Totem", "Totem", "Totem"),
    "widget_label": ("Totem", "Totem", "Totem", "Totem", "Totem"),
    "widget_description": (
        "Laat zien of er een blokkade loopt.",
        "Shows whether a block is running.",
        "Indique si un blocage est en cours.",
        "Muestra si hay un bloqueo en curso.",
        "Zeigt, ob eine Sperre läuft."),
    "accessibility_label": (
        "Totem — apps blokkeren",
        "Totem — block apps",
        "Totem — bloquer des apps",
        "Totem — bloquear apps",
        "Totem — Apps sperren"),
    "accessibility_description": (
        "Totem kijkt welke app je opent en toont een blokkadescherm zolang een focusmodus loopt. Er wordt niets gelezen of bewaard van wat er op je scherm staat.",
        "Totem checks which app you open and shows a block screen while a focus mode is running. Nothing on your screen is read or stored.",
        "Totem regarde quelle app tu ouvres et affiche un écran de blocage tant qu’un mode concentration est actif. Rien de ce qui est à l’écran n’est lu ni enregistré.",
        "Totem comprueba qué app abres y muestra una pantalla de bloqueo mientras hay un modo de concentración activo. No se lee ni se guarda nada de lo que hay en tu pantalla.",
        "Totem prüft, welche App du öffnest, und zeigt einen Sperrbildschirm, solange ein Fokusmodus läuft. Nichts auf deinem Bildschirm wird gelesen oder gespeichert."),

    # --- Blokkadescherm -----------------------------------------------------
    "block_title": (
        "%1$s is geblokkeerd",
        "%1$s is blocked",
        "%1$s est bloqué",
        "%1$s está bloqueada",
        "%1$s ist gesperrt"),
    "block_body": (
        "Je hebt gekozen voor focus. Tik je Totem aan als je %1$s weer wilt gebruiken.",
        "You chose focus. Tap your Totem when you want to use %1$s again.",
        "Tu as choisi la concentration. Tape ton Totem quand tu veux utiliser %1$s à nouveau.",
        "Has elegido concentrarte. Toca tu Totem cuando quieras volver a usar %1$s.",
        "Du hast dich für Fokus entschieden. Tippe auf dein Totem, wenn du %1$s wieder nutzen willst."),
    "block_this_app": ("Deze app", "This app", "Cette app", "Esta app", "Diese App"),
    "block_back_to_life": (
        "Terug naar het leven",
        "Back to real life",
        "Retour à la vraie vie",
        "Vuelve a la vida real",
        "Zurück ins echte Leben"),
    # --- Algemeen, deel 2 ---------------------------------------------------
    "unknown": ("Onbekend", "Unknown", "Inconnu", "Desconocido", "Unbekannt"),

    # --- Meldingen ----------------------------------------------------------
    "channel_session": ("Lopende blokkade", "Running block", "Blocage en cours", "Bloqueo en curso", "Laufende Sperre"),
    "channel_session_description": (
        "De teller die loopt zolang een blokkade actief is.",
        "The timer that runs while a block is active.",
        "Le compteur qui tourne tant qu’un blocage est actif.",
        "El contador que corre mientras hay un bloqueo activo.",
        "Der Zähler, der läuft, solange eine Sperre aktiv ist."),
    "channel_schedule": ("Schema's", "Schedules", "Programmes", "Horarios", "Zeitpläne"),
    "channel_schedule_description": (
        "Bericht zodra een schema een blokkade start of stopt.",
        "A message as soon as a schedule starts or stops a block.",
        "Un message dès qu’un programme lance ou arrête un blocage.",
        "Un aviso en cuanto un horario inicia o detiene un bloqueo.",
        "Eine Nachricht, sobald ein Zeitplan eine Sperre startet oder beendet."),
    "notify_started_title": ("%1$s is gestart", "%1$s has started", "%1$s a commencé", "%1$s ha empezado", "%1$s hat begonnen"),
    "notify_started_until": ("Je telefoon is rustig tot %1$s.", "Your phone is quiet until %1$s.", "Ton téléphone reste calme jusqu’à %1$s.", "Tu teléfono estará tranquilo hasta %1$s.", "Dein Handy ist ruhig bis %1$s."),
    "notify_started_tap": ("Tik je Totem aan als je weer verder wilt.", "Tap your Totem when you want to carry on.", "Tape ton Totem quand tu veux reprendre.", "Toca tu Totem cuando quieras seguir.", "Tippe auf dein Totem, wenn du weitermachen willst."),
    "notify_ended_title": ("%1$s is afgelopen", "%1$s has ended", "%1$s est terminé", "%1$s ha terminado", "%1$s ist beendet"),
    "notify_ended_body": ("Je apps zijn weer vrij.", "Your apps are free again.", "Tes apps sont de nouveau libres.", "Tus apps vuelven a estar libres.", "Deine Apps sind wieder frei."),
    "notify_refrozen_title": ("%1$s is weer actief", "%1$s is active again", "%1$s est de nouveau actif", "%1$s vuelve a estar activo", "%1$s ist wieder aktiv"),
    "notify_refrozen_body": ("Je pauze is voorbij; je apps zijn weer bevroren.", "Your break is over; your apps are frozen again.", "Ta pause est terminée ; tes apps sont de nouveau gelées.", "Tu pausa ha terminado; tus apps vuelven a estar congeladas.", "Deine Pause ist vorbei; deine Apps sind wieder eingefroren."),
    "notify_cannot_block_title": ("%1$s kon niet starten", "%1$s couldn’t start", "%1$s n’a pas pu démarrer", "%1$s no pudo iniciarse", "%1$s konnte nicht starten"),
    "notify_cannot_block_body": (
        "Totem mist een toestemming. Open de app en controleer de instellingen.",
        "Totem is missing a permission. Open the app and check the settings.",
        "Il manque une autorisation à Totem. Ouvre l’app et vérifie les réglages.",
        "A Totem le falta un permiso. Abre la app y revisa los ajustes.",
        "Totem fehlt eine Berechtigung. Öffne die App und prüfe die Einstellungen."),

    # --- Ontdooien -----------------------------------------------------------
    "detail_paused_label": ("Ontdooid, bevriest weer over", "Unfrozen, freezes again in", "Dégelé, se regèle dans", "Descongelado, se congela de nuevo en", "Aufgetaut, friert wieder ein in"),
    "detail_freeze_now": ("Nu weer bevriezen", "Freeze again now", "Regeler maintenant", "Volver a congelar ya", "Jetzt wieder einfrieren"),
    "detail_unfreeze_minutes": ("%1$d min ontdooien", "Unfreeze for %1$d min", "Dégeler %1$d min", "Descongelar %1$d min", "%1$d Min. auftauen"),
    "detail_deactivate": ("Totem deactiveren", "Deactivate Totem", "Désactiver Totem", "Desactivar Totem", "Totem deaktivieren"),
    "detail_activate": ("Totem activeren", "Activate Totem", "Activer Totem", "Activar Totem", "Totem aktivieren"),
    "detail_block_time": ("Blokkade tijd", "Block time", "Temps de blocage", "Tiempo de bloqueo", "Sperrzeit"),
    "scan_unfreeze": ("Tik je Totem aan om %1$d minuten te ontdooien", "Tap your Totem to unfreeze for %1$d minutes", "Tape ton Totem pour dégeler %1$d minutes", "Toca tu Totem para descongelar %1$d minutos", "Tippe auf dein Totem, um %1$d Minuten aufzutauen"),
    "editor_unfreeze_on_tap": ("Ontdooien bij tikken", "Unfreeze on tap", "Dégeler en tapant", "Descongelar al tocar", "Beim Tippen auftauen"),
    "editor_unfreeze_minutes": ("%1$d min", "%1$d min", "%1$d min", "%1$d min", "%1$d Min."),
    "editor_unfreeze_help": (
        "Tik je tijdens het schema je Totem aan, dan ontdooien je apps even en bevriezen ze daarna weer tot het schema voorbij is.",
        "Tap your Totem during the schedule and your apps unfreeze for a moment, then freeze again until the schedule ends.",
        "Si tu tapes ton Totem pendant le programme, tes apps se dégèlent un moment puis se regèlent jusqu’à la fin du programme.",
        "Si tocas tu Totem durante el horario, tus apps se descongelan un momento y luego se vuelven a congelar hasta que termine el horario.",
        "Tippst du während des Zeitplans auf dein Totem, tauen deine Apps kurz auf und frieren danach wieder ein, bis der Zeitplan vorbei ist."),
    # --- Modusnamen ---------------------------------------------------------
    "mode_work": ("Werk", "Work", "Travail", "Trabajo", "Arbeit"),
    "mode_sport": ("Sport", "Sport", "Sport", "Deporte", "Sport"),
    "mode_relax": ("Relaxen", "Relax", "Détente", "Relax", "Entspannen"),
    "mode_study": ("Studeren", "Study", "Études", "Estudiar", "Lernen"),
    "mode_sleep": ("Slaap", "Sleep", "Sommeil", "Dormir", "Schlafen"),
    "mode_other": ("Anders…", "Other…", "Autre…", "Otro…", "Anderes …"),
    # --- Hoofdscherm ----------------------------------------------------------
    "mode_blocked_count": ("%1$d geblokkeerd", "%1$d blocked", "%1$d bloquées", "%1$d bloqueadas", "%1$d gesperrt"),
    "mode_no_apps": ("Nog geen apps gekozen", "No apps chosen yet", "Aucune app choisie", "Aún no hay apps elegidas", "Noch keine Apps gewählt"),
    "home_add_mode": ("Modus toevoegen", "Add mode", "Ajouter un mode", "Añadir modo", "Modus hinzufügen"),
    "home_swipe_hint": ("Veeg een modus naar links om hem te verwijderen.", "Swipe a mode to the left to delete it.", "Balaie un mode vers la gauche pour le supprimer.", "Desliza un modo hacia la izquierda para borrarlo.", "Wische einen Modus nach links, um ihn zu löschen."),
    "home_activate_mode": ("%1$s activeren", "Activate %1$s", "Activer %1$s", "Activar %1$s", "%1$s aktivieren"),
    "home_activate_hint": ("Houd daarna je telefoon tegen je Totem.", "Then hold your phone against your Totem.", "Ensuite, approche ton téléphone de ton Totem.", "Después, acerca tu teléfono a tu Totem.", "Halte dann dein Handy an dein Totem."),
    "home_activate_hint_empty": ("Kies eerst apps in een modus om te kunnen activeren.", "First choose apps in a mode to be able to activate.", "Choisis d’abord des apps dans un mode pour pouvoir activer.", "Elige primero apps en un modo para poder activarlo.", "Wähle zuerst Apps in einem Modus, um aktivieren zu können."),
    "home_permission_title": ("Totem kan nog niets blokkeren", "Totem can’t block anything yet", "Totem ne peut encore rien bloquer", "Totem aún no puede bloquear nada", "Totem kann noch nichts sperren"),
    "home_permission_body": (
        "Geef toegankelijkheid en ‘over andere apps tekenen’ vrij in de instellingen.",
        "Allow accessibility and ‘display over other apps’ in the settings.",
        "Autorise l’accessibilité et « superposition sur d’autres apps » dans les réglages.",
        "Permite la accesibilidad y «mostrar sobre otras apps» en los ajustes.",
        "Erlaube Bedienungshilfen und „Über anderen Apps einblenden“ in den Einstellungen."),
    "choose_title": ("Welke modus wil je starten?", "Which mode do you want to start?", "Quel mode veux-tu lancer ?", "¿Qué modo quieres iniciar?", "Welchen Modus möchtest du starten?"),
    "delete_title": ("‘%1$s’ verwijderen?", "Delete ‘%1$s’?", "Supprimer « %1$s » ?", "¿Borrar «%1$s»?", "„%1$s“ löschen?"),
    "delete_body": ("De gekozen apps en het schema van deze modus ben je dan kwijt.", "You’ll lose the chosen apps and the schedule of this mode.", "Tu perdras les apps choisies et le programme de ce mode.", "Perderás las apps elegidas y el horario de este modo.", "Die gewählten Apps und der Zeitplan dieses Modus gehen dann verloren."),
    "delete_confirm": ("Verwijderen", "Delete", "Supprimer", "Borrar", "Löschen"),
    "cancel": ("Annuleer", "Cancel", "Annuler", "Cancelar", "Abbrechen"),
    "stats_title": ("Statistieken", "Statistics", "Statistiques", "Estadísticas", "Statistiken"),
    "settings_title": ("Instellingen", "Settings", "Réglages", "Ajustes", "Einstellungen"),
    "error_max_modes": ("Je kunt maximaal %1$d modi maken. Verwijder er eerst een.", "You can create up to %1$d modes. Delete one first.", "Tu peux créer au maximum %1$d modes. Supprimes-en un d’abord.", "Puedes crear un máximo de %1$d modos. Borra uno primero.", "Du kannst höchstens %1$d Modi erstellen. Lösche zuerst einen."),

    # --- Schema-samenvattingen ----------------------------------------------
    "sched_time_summary": ("%1$s  %2$s – %3$s", "%1$s  %2$s – %3$s", "%1$s  %2$s – %3$s", "%1$s  %2$s – %3$s", "%1$s  %2$s – %3$s"),
    "sched_location_summary": ("%1$s  bij %2$s – %3$s", "%1$s  at %2$s – %3$s", "%1$s  à %2$s – %3$s", "%1$s  en %2$s – %3$s", "%1$s  bei %2$s – %3$s"),
    "sched_until_tap": ("tot je tikt", "until you tap", "jusqu’à ce que tu tapes", "hasta que toques", "bis du tippst"),
    "sched_until_leave": ("tot je weggaat", "until you leave", "jusqu’à ce que tu partes", "hasta que te vayas", "bis du gehst"),
    "sched_every_day": ("elke dag", "every day", "tous les jours", "todos los días", "jeden Tag"),
    "sched_weekend": ("weekend", "weekend", "week-end", "fin de semana", "Wochenende"),
    "sched_no_day": ("geen dag", "no days", "aucun jour", "ningún día", "kein Tag"),
    "sched_no_place": ("geen locatie gekozen", "no location chosen", "aucun lieu choisi", "sin ubicación elegida", "kein Ort gewählt"),

    # --- Locatie -------------------------------------------------------------
    "notify_until_leave": ("je weggaat", "you leave", "ton départ", "que te vayas", "du gehst"),
    "loc_title": ("Locatie", "Location", "Lieu", "Ubicación", "Ort"),
    "loc_search_hint": ("Zoek een plek of adres", "Search for a place or address", "Cherche un lieu ou une adresse", "Busca un lugar o una dirección", "Suche einen Ort oder eine Adresse"),
    "loc_search": ("Zoek", "Search", "Rechercher", "Buscar", "Suchen"),
    "loc_current": ("Gebruik mijn huidige locatie", "Use my current location", "Utiliser ma position actuelle", "Usar mi ubicación actual", "Meinen aktuellen Standort verwenden"),
    "loc_no_results": ("Niets gevonden. Probeer een ander adres.", "Nothing found. Try another address.", "Rien trouvé. Essaie une autre adresse.", "No se encontró nada. Prueba otra dirección.", "Nichts gefunden. Versuch eine andere Adresse."),
    "loc_radius": ("Straal: %1$d m", "Radius: %1$d m", "Rayon : %1$d m", "Radio: %1$d m", "Radius: %1$d m"),
    "loc_radius_help": (
        "Zodra je binnen deze cirkel komt, begint de modus. Android merkt dat niet op de meter nauwkeurig; een straal van 150 m of meer werkt het betrouwbaarst.",
        "The mode starts as soon as you enter this circle. Android doesn’t detect this to the metre; a radius of 150 m or more works most reliably.",
        "Le mode démarre dès que tu entres dans ce cercle. Android ne le détecte pas au mètre près ; un rayon de 150 m ou plus est le plus fiable.",
        "El modo empieza en cuanto entras en este círculo. Android no lo detecta al metro; un radio de 150 m o más es lo más fiable.",
        "Sobald du diesen Kreis betrittst, beginnt der Modus. Android erkennt das nicht metergenau; ein Radius von 150 m oder mehr ist am zuverlässigsten."),
    "loc_choose": ("Kies locatie", "Choose location", "Choisir un lieu", "Elegir ubicación", "Ort wählen"),
    "loc_default_name": ("Locatie", "Location", "Lieu", "Ubicación", "Ort"),
    "loc_perm_title": ("Locatietoegang ‘Altijd toestaan’ nodig", "Location access ‘Allow all the time’ needed", "Accès à la position « Toujours autoriser » requis", "Se necesita acceso a la ubicación «Permitir todo el tiempo»", "Standortzugriff „Immer zulassen“ nötig"),
    "loc_perm_body": (
        "Alleen dan kan Totem de modus starten als de app dicht is. Je locatie blijft op je telefoon; Totem kijkt alleen of je bij deze plek bent.",
        "Only then can Totem start the mode while the app is closed. Your location stays on your phone; Totem only checks whether you’re at this place.",
        "C’est la seule façon pour Totem de lancer le mode quand l’app est fermée. Ta position reste sur ton téléphone ; Totem vérifie seulement si tu es à cet endroit.",
        "Solo así Totem puede iniciar el modo con la app cerrada. Tu ubicación se queda en tu teléfono; Totem solo comprueba si estás en este lugar.",
        "Nur dann kann Totem den Modus starten, wenn die App geschlossen ist. Dein Standort bleibt auf deinem Handy; Totem prüft nur, ob du an diesem Ort bist."),
    "loc_perm_button": ("Toestemming geven", "Give permission", "Autoriser", "Dar permiso", "Erlauben"),
    "loc_perm_settings": ("Open instellingen", "Open settings", "Ouvrir les réglages", "Abrir ajustes", "Einstellungen öffnen"),
    "sched_trigger_time": ("Op tijd", "At a time", "À une heure", "A una hora", "Nach Zeit"),
    "sched_trigger_location": ("Op locatie", "By location", "Selon le lieu", "Por ubicación", "Nach Ort"),
    "sched_end_leave": ("Als je weggaat", "When you leave", "Quand tu pars", "Cuando te vayas", "Wenn du gehst"),
    "sched_end_tap": ("Als je tikt", "When you tap", "Quand tu tapes", "Cuando toques", "Wenn du tippst"),
    "sched_ends": ("Eindigt", "Ends", "Se termine", "Termina", "Endet"),
    "sched_location_help": (
        "Deze modus begint vanzelf als je op de gekozen dagen bij deze plek aankomt. Kies je ‘Als je tikt’, dan stopt de blokkade pas als je je Totem aantikt, ook als je weggaat.",
        "This mode starts automatically when you arrive at this place on the chosen days. Choose ‘When you tap’ and the block only stops when you tap your Totem, even if you leave.",
        "Ce mode démarre automatiquement quand tu arrives à cet endroit les jours choisis. Choisis « Quand tu tapes » et le blocage ne s’arrête que lorsque tu tapes ton Totem, même si tu pars.",
        "Este modo empieza solo cuando llegas a este lugar en los días elegidos. Elige «Cuando toques» y el bloqueo solo termina al tocar tu Totem, aunque te vayas.",
        "Dieser Modus beginnt automatisch, wenn du an den gewählten Tagen an diesem Ort ankommst. Wählst du „Wenn du tippst“, endet die Sperre erst, wenn du dein Totem antippst – auch wenn du gehst."),
    "done": ("Gereed", "Done", "OK", "Listo", "Fertig"),

    # --- Wizard ----------------------------------------------------------------
    "back": ("Terug", "Back", "Retour", "Atrás", "Zurück"),
    "wiz_skip": ("Overslaan", "Skip", "Passer", "Omitir", "Überspringen"),
    "wiz_next": ("Volgende", "Next", "Suivant", "Siguiente", "Weiter"),
    "wiz_finish": ("Klaar", "Done", "Terminé", "Listo", "Fertig"),
    "wiz_purpose_first": ("Waarvoor wil je Totem gebruiken?", "What do you want to use Totem for?", "Pour quoi veux-tu utiliser Totem ?", "¿Para qué quieres usar Totem?", "Wofür möchtest du Totem nutzen?"),
    "wiz_purpose_first_sub": ("We beginnen met één modus. Later kun je er meer toevoegen.", "We’ll start with one mode. You can add more later.", "On commence avec un mode. Tu pourras en ajouter d’autres plus tard.", "Empezamos con un modo. Más adelante puedes añadir más.", "Wir beginnen mit einem Modus. Später kannst du weitere hinzufügen."),
    "wiz_purpose_new": ("Waarvoor is je nieuwe modus?", "What’s your new mode for?", "À quoi sert ton nouveau mode ?", "¿Para qué es tu nuevo modo?", "Wofür ist dein neuer Modus?"),
    "wiz_purpose_new_sub": ("Dan zetten we alvast klaar wat daarbij past.", "We’ll set up what fits right away.", "On prépare tout de suite ce qui va avec.", "Así preparamos lo que mejor encaja.", "Dann bereiten wir gleich vor, was dazu passt."),
    "wiz_work_sub": ("Geconcentreerd doorwerken", "Work with full focus", "Travailler concentré", "Trabajar concentrado", "Konzentriert arbeiten"),
    "wiz_sport_sub_tile": ("Trainen zonder je telefoon", "Train without your phone", "S’entraîner sans ton téléphone", "Entrenar sin tu teléfono", "Trainieren ohne Handy"),
    "wiz_relax_sub": ("Echt even offline", "Truly offline for a while", "Vraiment hors ligne un moment", "Desconectar de verdad un rato", "Wirklich mal offline"),
    "wiz_study_sub": ("Leren zonder afleiding", "Learn without distraction", "Apprendre sans distraction", "Aprender sin distracciones", "Lernen ohne Ablenkung"),
    "wiz_other_sub": ("Je geeft hem zelf een naam", "You give it a name yourself", "Tu lui donnes toi-même un nom", "Le pones tú el nombre", "Du gibst ihm selbst einen Namen"),
    "wiz_name_label": ("Hoe heet je modus?", "What’s your mode called?", "Comment s’appelle ton mode ?", "¿Cómo se llama tu modo?", "Wie heißt dein Modus?"),
    "wiz_name_hint": ("Bijv. Studeren", "E.g. Study", "Ex. Études", "Ej. Estudiar", "z. B. Lernen"),
    "wiz_apps_title": ("Welke apps leiden je af tijdens %1$s?", "Which apps distract you during %1$s?", "Quelles apps te distraient pendant %1$s ?", "¿Qué apps te distraen durante %1$s?", "Welche Apps lenken dich bei %1$s ab?"),
    "wiz_apps_sub": ("Die gaan op slot zolang %1$s aan staat.", "They’re locked while %1$s is on.", "Elles sont verrouillées tant que %1$s est actif.", "Se bloquean mientras %1$s esté activo.", "Sie werden gesperrt, solange %1$s an ist."),
    "wiz_apps_tip": ("Kies de apps die je het vaakst zonder nadenken opent, zoals Instagram, TikTok of YouTube.", "Pick the apps you open most often without thinking, like Instagram, TikTok or YouTube.", "Choisis les apps que tu ouvres le plus souvent sans réfléchir, comme Instagram, TikTok ou YouTube.", "Elige las apps que más abres sin pensar, como Instagram, TikTok o YouTube.", "Wähle die Apps, die du am häufigsten ohne nachzudenken öffnest, wie Instagram, TikTok oder YouTube."),
    "wiz_apps_choose": ("Kies apps", "Choose apps", "Choisir des apps", "Elegir apps", "Apps wählen"),
    "wiz_apps_chosen": ("%1$d gekozen · aanpassen", "%1$d chosen · edit", "%1$d choisies · modifier", "%1$d elegidas · editar", "%1$d gewählt · ändern"),
    "wiz_sport_title": ("Automatisch aan in de sportschool?", "Turn on automatically at the gym?", "Activer automatiquement à la salle de sport ?", "¿Activar automáticamente en el gimnasio?", "Im Fitnessstudio automatisch an?"),
    "wiz_sport_sub": ("Zodra je binnenkomt gaat Sport aan, en als je weggaat weer uit.", "Sport turns on as soon as you walk in, and off again when you leave.", "Sport s’active dès que tu entres, et se désactive quand tu pars.", "Deporte se activa en cuanto entras y se desactiva al salir.", "Sobald du hereinkommst, geht Sport an, und wenn du gehst, wieder aus."),
    "wiz_sport_yes": ("Ja, op locatie", "Yes, by location", "Oui, selon le lieu", "Sí, por ubicación", "Ja, nach Ort"),
    "wiz_sport_yes_sub": ("Kies je sportschool", "Pick your gym", "Choisis ta salle de sport", "Elige tu gimnasio", "Wähle dein Fitnessstudio"),
    "wiz_sport_no": ("Nee, ik start zelf", "No, I’ll start it myself", "Non, je le lance moi-même", "No, lo inicio yo", "Nein, ich starte selbst"),
    "wiz_sport_no_sub": ("Met een tik op je Totem", "With a tap on your Totem", "D’un tap sur ton Totem", "Con un toque en tu Totem", "Mit einem Tipp auf dein Totem"),
    "wiz_when_title": ("Wanneer moet %1$s vanzelf aangaan?", "When should %1$s turn on by itself?", "Quand %1$s doit-il s’activer tout seul ?", "¿Cuándo debe activarse %1$s solo?", "Wann soll %1$s von selbst angehen?"),
    "wiz_when_sub": ("Je kunt hem altijd ook zelf starten met je Totem.", "You can always start it yourself with your Totem too.", "Tu peux toujours le lancer toi-même avec ton Totem.", "También puedes iniciarlo tú siempre con tu Totem.", "Du kannst ihn auch jederzeit selbst mit deinem Totem starten."),
    "wiz_opt_time": ("Op vaste tijden", "At set times", "À heures fixes", "A horas fijas", "Zu festen Zeiten"),
    "wiz_opt_time_sub": ("Bijvoorbeeld ma–vr 9:00–17:00", "For example Mon–Fri 9:00–17:00", "Par exemple lun–ven 9:00–17:00", "Por ejemplo lun–vie 9:00–17:00", "Zum Beispiel Mo–Fr 9:00–17:00"),
    "wiz_opt_location": ("Op locatie", "By location", "Selon le lieu", "Por ubicación", "Nach Ort"),
    "wiz_opt_location_work": ("Bijvoorbeeld zodra je op kantoor bent", "For example as soon as you’re at the office", "Par exemple dès que tu es au bureau", "Por ejemplo en cuanto estés en la oficina", "Zum Beispiel, sobald du im Büro bist"),
    "wiz_opt_location_study": ("Bijvoorbeeld in de bibliotheek", "For example at the library", "Par exemple à la bibliothèque", "Por ejemplo en la biblioteca", "Zum Beispiel in der Bibliothek"),
    "wiz_opt_location_other": ("Zodra je op een gekozen plek bent", "As soon as you’re at a chosen place", "Dès que tu es à un endroit choisi", "En cuanto estés en un lugar elegido", "Sobald du an einem gewählten Ort bist"),
    "wiz_opt_none": ("Niet automatisch", "Not automatically", "Pas automatiquement", "No automáticamente", "Nicht automatisch"),
    "wiz_opt_none_sub": ("Je start zelf met je Totem", "You start it yourself with your Totem", "Tu le lances toi-même avec ton Totem", "Lo inicias tú con tu Totem", "Du startest selbst mit deinem Totem"),
    "wiz_from": ("Van", "From", "De", "Desde", "Von"),
    "wiz_to": ("Tot", "Until", "À", "Hasta", "Bis"),
    "wiz_done_title": ("%1$s staat klaar", "%1$s is ready", "%1$s est prêt", "%1$s está listo", "%1$s ist bereit"),
    "wiz_done_sub": ("Houd je telefoon tegen je Totem om te starten. Tik nog een keer om te stoppen.", "Hold your phone against your Totem to start. Tap again to stop.", "Approche ton téléphone de ton Totem pour démarrer. Tape à nouveau pour arrêter.", "Acerca tu teléfono a tu Totem para empezar. Vuelve a tocar para detener.", "Halte dein Handy an dein Totem, um zu starten. Tippe noch einmal, um zu beenden."),
    "tip_emergency": ("Totem kwijt tijdens een blokkade? Tik 3 keer snel op de Totem-afbeelding voor een noodontgrendeling.", "Lost your Totem during a block? Quickly tap the Totem image 3 times for an emergency unlock.", "Tu as perdu ton Totem pendant un blocage ? Tape 3 fois rapidement sur l’image du Totem pour un déverrouillage d’urgence.", "¿Has perdido tu Totem durante un bloqueo? Toca 3 veces rápido la imagen del Totem para un desbloqueo de emergencia.", "Totem während einer Sperre verloren? Tippe 3-mal schnell auf das Totem-Bild für eine Notentsperrung."),

    # --- Promotiescherm ------------------------------------------------------
    "close": ("Sluiten", "Close", "Fermer", "Cerrar", "Schließen"),
    "promo_feedback_title": ("Hoe bevalt ‘%1$s’?", "How do you like ‘%1$s’?", "Que penses-tu de « %1$s » ?", "¿Qué te parece «%1$s»?", "Wie gefällt dir „%1$s“?"),
    "promo_feedback_good": ("Goed, houden zo :)", "Great, keep it up :)", "Super, on continue :)", "Genial, así se queda :)", "Super, so bleibt’s :)"),
    "promo_feedback_better": ("Kan beter, nu aanpassen", "Could be better, edit now", "Peut mieux faire, modifier", "Puede mejorar, editar ahora", "Geht besser, jetzt ändern"),
    "promo_tip_label": ("Totem weetje", "Totem tip", "Astuce Totem", "Truco Totem", "Totem-Tipp"),
    "promo_tip_title": ("Wist je dat…", "Did you know…", "Le savais-tu…", "Sabías que…", "Wusstest du …"),
    "promo_tip_ok": ("Handig!", "Handy!", "Pratique !", "¡Qué útil!", "Praktisch!"),
    "promo_schedule_title": ("Schema’s tegen doomscrollen", "Schedules against doomscrolling", "Des programmes contre le doomscrolling", "Horarios contra el doomscrolling", "Zeitpläne gegen Doomscrolling"),
    "promo_schedule_body": ("Jij kiest wanneer het schema activeert. Totem gaat dan vanzelf aan.", "You choose when the schedule kicks in. Totem then turns on by itself.", "Tu choisis quand le programme s’active. Totem se lance alors tout seul.", "Tú eliges cuándo se activa el horario. Totem se enciende solo.", "Du wählst, wann der Zeitplan startet. Totem geht dann von selbst an."),
    "promo_schedule_button": ("Schema instellen", "Set up a schedule", "Créer un programme", "Configurar un horario", "Zeitplan einrichten"),
    "promo_location_title": ("Brainrot uitschakelen op de locatie die jij kiest", "Switch off brainrot at the place you choose", "Coupe le brainrot à l’endroit de ton choix", "Apaga el brainrot en el lugar que elijas", "Brainrot abschalten an dem Ort, den du wählst"),
    "promo_location_body": ("Bijvoorbeeld in de sportschool: zodra je binnenkomt gaat je modus aan.", "At the gym, for example: your mode turns on as soon as you walk in.", "À la salle de sport, par exemple : ton mode s’active dès que tu entres.", "En el gimnasio, por ejemplo: tu modo se activa en cuanto entras.", "Zum Beispiel im Fitnessstudio: Sobald du hereinkommst, geht dein Modus an."),
    "promo_location_button": ("Activeer locatiebescherming", "Turn on location protection", "Activer la protection par lieu", "Activar la protección por ubicación", "Ortsschutz aktivieren"),
    "tip_any_totem": ("Elke Totem werkt: start op kantoor met de Totem die daar ligt en stop thuis met je eigen.", "Any Totem works: start at the office with the Totem there and stop at home with your own.", "N’importe quel Totem fonctionne : démarre au bureau avec le Totem qui s’y trouve et arrête chez toi avec le tien.", "Cualquier Totem sirve: empieza en la oficina con el Totem de allí y termina en casa con el tuyo.", "Jedes Totem funktioniert: Starte im Büro mit dem Totem dort und beende zu Hause mit deinem eigenen."),
    "tip_strict": ("Zet in Instellingen de strikte modus aan. Dan vraagt ook de noodontgrendeling om je pincode.", "Turn on strict mode in Settings. Then the emergency unlock asks for your PIN too.", "Active le mode strict dans Réglages. Le déverrouillage d’urgence demandera alors aussi ton code.", "Activa el modo estricto en Ajustes. Así el desbloqueo de emergencia también pedirá tu PIN.", "Schalte in den Einstellungen den strengen Modus ein. Dann fragt auch die Notentsperrung nach deiner PIN."),
    "tip_tap_closed": ("Tik je Totem aan terwijl de app dicht is: je kiest dan meteen welke modus start.", "Tap your Totem while the app is closed: you pick right away which mode starts.", "Tape ton Totem quand l’app est fermée : tu choisis tout de suite le mode à lancer.", "Toca tu Totem con la app cerrada: eliges al momento qué modo empieza.", "Tippe auf dein Totem, während die App geschlossen ist: Du wählst sofort, welcher Modus startet."),
}